go-ego/gse

- .travis.yml
- circle.yml
- segmenter_test.go
> add more test

- README_zh.md
> fix typo for example

- segmenter.go
- segmenter_test.go
- utils.go
> Fix sub-word error

- dict_util.go
- segmenter.go
- segmenter_test.go
- testdata/test_dict3.txt
- add alphanum split words support
- Fixed #15
> add alphanum split words support

- dict_util.go
when loading dictionary, if frequency is not specified, currently defaults to 2. however i want to be able to control the default value. is it ok to provide an exported variable (as in my commit), so user may be able to change it.
forgive my english :-)
> use variable to control default frequency

- dict_util.go
- dictionary.go
- gse.go
- segmenter_test.go
- add remove token support
- update version
> add remove token support

- segmenter.go
- segmenter_test.go
> add ToLower set support

- gse.go
- segmenter_test.go
- add Trim punct and space function support
- #16
> add Trim punct and space function support

- examples/example.go
- gse.go
- update Trim function not exclude "include other char string"
> update Trim function not exclude "include other char string"

- dict_util.go
- segmenter_test.go
- update DictPaths() allow use ", " to separated dictionary files
> update DictPaths() allow use ", " to separated dictionary files

- dag.go
- segmenter_test.go
- add cutDAGNoHMM support and test code
> add cutDAGNoHMM support

- gse.go
- gse_bm_test.go
- segmenter_test.go
- add Cut() function cutDAGNoHMM option support
> add Cut() function cutDAGNoHMM option support

- dict_util.go
- hmm/pos/pos_seg.go
- hmm/pos/pos_seg_test.go
- segmenter_test.go
- add skip log set support
- add more hmm pos test and remove unused make
> add skip log set support

- dag.go
- dict_util.go
- dictionary.go
- hmm/pos/dict.go
- hmm/pos/pos_seg.go
- segmenter_test.go
- token.go
- update frequency type to float64, reduce type conversion and make type same
- remove float64 type conversion
> update frequency type to float64, reduce type conversion

- README.md
- README_zh.md
- examples/dict/main.go
- examples/jp/main.go
- examples/main.go
- gse.go
- gse_bm_test.go
- segmenter_test.go
- update string() and slice() use string not []byte, reduce type conver
- Update examples and README.md
> update string() and slice() use string not []byte, reduce type conver

- gse.go
- gse_test.go
- segmenter_test.go
- add SegPos and TrimPos support
> add SegPos and TrimPos support

- gse.go
- hmm/pos/pos_seg.go
- add pos WitheGse and Trim support
> add pos WitheGse and Trim support

- gse.go
- gse_test.go
- hmm/pos/pos_seg.go
- add TrimPunct and TrimPos function support and test
> add TrimPunct and TrimPos function support and test

- dag.go
- gse_test.go
- add suggest frequency support
> add suggest frequency support

- gse.go
- gse_test.go
- hmm/pos/pos_seg.go
- hmm/pos/pos_seg_test.go
- Fixed TrimPos multi-pos error
- Add more test
> Fixed TrimPos multi-pos error

- dict_util.go
- gse_bm_test.go
- gse_test.go
- segmenter.go
- segmenter_test.go
- token_test.go
- Add multi load dictionary support
- Refactor test code
> add multi load dictionary support

- hmm/pos/pos_seg.go
- optimize the pos cutDAG code
> optimize the pos cutDAG code

- dict_util.go
- examples/main.go
- gse.go
- gse_test.go
- hmm/idf/idf.go
- hmm/idf/idf_test.go
- seg_utils.go
- segmenter_test.go
- stop.go
- add idf default dictionary load support
- optimize seg Pos not split
- add Seg Pos search mode support
- add tag extracter and text ranker examples
- move idf.txt to data [ci skip]
- add more test code
> add idf default dictionary load support and optimize segPos not split

- gse.go
- gse_test.go
- add cut to string and pos to string support
> add CutStr and PosStr support

- gse.go
- stop.go
> add trim IsStop() support

- gse.go
- gse_test.go
- add cut and pos trim combination support
> add CutTrim() and PosTrim() support

- gse.go
- gse_test.go
- add pos trim array and string support
- add pos trim test code
> add pos trim array and string support

- gse.go
- gse_test.go
> add filter symbol and emoji support

- gse.go
- gse_test.go
> add more filter function

- gse_test.go
> add more test code

- hmm/idf/stop_words.go
> optimize idf stop word code

- hmm/pos/pos_seg.go
> optimize pos code

- dictionary.go
- hmm/idf/tag_extracker.go
- hmm/idf/textrank.go
- hmm/pos/pos_seg.go
- hmm/pos/viterbi.go
- hmm/viterbi.go
- update godoc and optimize code
- optimize HMM code
> update godoc and optimize code

- benchmark/goroutines/goroutines.go
- dag.go
- gse.go
- hmm/hmm_seg.go
- hmm/hmm_seg_test.go
- seg_utils.go
- server/server.go
- token.go
- optimize some code
- update hmm seg test code
> update test code and optimize code

- dict_util.go
- segmenter.go
- segmenter_test.go
- optimize segmenter option not use var
> optimize segmenter option not use var

- gse.go
- gse_test.go
- segmenter.go
- add PosStr SkipPos support
- add skip pos test code
> add PosStr SkipPos support

- dict_util.go
- segmenter.go
- segmenter_test.go
- stop.go
> add SkipLog and MoreLog option support

- gse_test.go
- trim.go
> add filter html support

- gse_test.go
- trim.go
> add more html filter support

- segmenter.go
- trim.go
> add NotStop option support

- hmm/pos/dict.go
- hmm/pos/pos_seg.go
- trim.go
> add all Stop option NotStop support

- examples/main.go
No, didn't create issue first.
- The `examples/main.go` cannot be run in https://play.golang.org/ as it will always timeout
- So adding all the result outputs will be the only way for people to know how the functions work, how the results look like, without installing the package and running the program
So I think the result comments will be helpful to people who don't know `gse` previously, and be helpful for `gse` to spread. thx.
> Add results as comments to examples/main.go

- gse_test.go
- trim.go
> add CutTrimHtml and TrimSymbol support

- gse_test.go
- hmm/idf/stop_words.go
- stop.go
> add RemoveStop function support

- dict_util.go
- gse.go
- gse_test.go
- segmenter.go
- segmenter_test.go
> add Num option support and  use seg.AlphaNum

- segmenter.go
- segmenter_test.go
> add splitWord() function

- gse_test.go
- trim.go
> add cut url function support

- gse_test.go
- segmenter.go
> add alpha option support

- circle.yml
- trim.go
> add cut url num option

- circle.yml
- dag.go
- seg.go
> update suggest, segment and  circle.yml

- dict_util.go
- trim.go
> update code and fixed godoc

- gse_test.go
- stop.go
> add LoadStopArr dictionary support

- dict_1.16.go
- dict_1.16_test.go
- go.mod
> add load dictionary by embed support

- dict_1.16.go
- dict_1.16_test.go
> add LoadStopEmbed support

- dict_1.16.go
- dict_1.16_test.go
> add NewEmbed segmenter support

- circle.yml
- examples/dict/main.go
> update examples code

- examples/dict/main.go
> add more load dictionary examples

- server/server.go
> add AddToken function code to server

- circle.yml
- examples/dict/main.go
- examples/en/main.go
**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**
- Issues: #
```Go
```
...
> update examples code and circle.yml

- dag.go
- gse_test.go
- seg.go
- Issues: #1, #68
```Go
```
...
> add analyze the token segment info function

- README.md
- README_zh.md
- examples/en/main.go
- examples/hmm/main.go
- examples/jp/main.go
> Update examples code and README.md

- dict_1.16.go
- dict_1.16_test.go
> Add more embed function and test code

- README.md
- README_zh.md
- examples/dict/main.go
- examples/en/main.go
- gse.go
- gse_test.go
- hmm/idf/idf_test.go
- segmenter_test.go
- testdata/test_dict3.txt
> add gse.New() error return support

- examples/dict/embed/main.go
- examples/dict/embed/test_dict3.txt
> add more embed examples code

- dag.go
- dict_1.16.go
- dict_1.16_test.go
- dictionary.go
- examples/en/main.go
- examples/main.go
- gse_test.go
- hmm/idf/idf.go
- hmm/idf/tag_extracker.go
- hmm/pos/dict.go
- hmm/pos/pos_seg.go
- seg.go
- segmenter_test.go
> add Find() function pos return support and more error return

- dict_util.go
- gse_test.go
> add empty dictionary function support

- README.md
- README_zh.md
- dict_1.16.go
- dict_util.go
- examples/dict/embed/main.go
- gse_test.go
- segmenter.go
- stop.go
> add empty the stop dictionary function and Update README.md

- README.md
- README_zh.md
- dict_1.16.go
- dict_util.go
- dictionary.go
> export dictionary addToken function

- dictionary.go
- go.mod
- go.sum
> switch to new cedar and update go mod

- dag.go
- dict_1.16.go
- dict_util.go
- dictionary.go
- examples/dict/main.go
- go.mod
- go.sum
- gse.go
- gse_test.go
- hmm/hmm_seg.go
- hmm/idf/idf.go
- hmm/idf/stop_words.go
- hmm/idf/tag_extracker.go
- hmm/idf/textrank.go
- hmm/pos/dict.go
- hmm/pos/pos_seg.go
- hmm/util/util.go
- hmm/viterbi.go
- segmenter.go
- segmenter_test.go
- server/server.go
- stop.go
- token.go
> add ReAddToken() function and unify name, Update go mod

- dag.go
- hmm/idf/idf.go
> add more IDF dictionary function and update godoc

- dag.go
- gse.go
- gse_test.go
- hmm/hmm_seg.go
- Issues: #114, #122
```Go
```
...
> add CutDAD with regexp and CutDAGNoHMM support

- README.md
- README_zh.md
- examples/hmm/main.go
- hmm/idf/stop_words.go
- stop.go
> add more examples code and Update README.md

- go.mod
- go.sum
> Update cedar to newest

- gse_test.go
- stop.go
- trim.go
> add more stop world function and test code

- README.md
- circle.yml
- go.mod
- go.sum
> Update README.md and go mod

- hmm/hmm_seg.go
> Add other language hmm cut with regexp index support

- dict_1.16.go
- dict_util.go
- segmenter_test.go
> add more language embed and option support

- circle.yml
- dict_1.16.go
- dict_embed.go
- dict_no_embed.go
> add no embed build tags support

- README.md
- examples/en/main.go
- examples/en/testdata/test_en.txt
- examples/en/testdata/test_en2.txt
- examples/en/testdata/test_en_dict3.txt
- testdata/test_en2.txt
> Add: add more examples and Update README.md

- dict_util.go
- dictionary.go
- gse.go
- gse_test.go
- segmenter.go
> Add: add load hmm model option and update godoc

- dict_embed.go
- gse.go
> Update: export zhidf and update godoc

- .github/workflows/go.yml
- circle.yml
> Update: bump CI

- .github/workflows/go.yml
- circle.yml
> Update: bump CI to newest

- .github/workflows/go.yml
- circle.yml
- go.mod
- go.sum
> Update: update go mod and CI to latest

- .github/workflows/go.yml
- circle.yml
> Update: update go CI

- README.md
- examples/main.go
> Update: update readme.md and examples
